language: java
env:
  global:
  - SIA_VERSION=1.3.3
script:
- gradle test --info
after_success:
- gradle jacocoTestReport coveralls
before_deploy:
- mkdir -p build/sia
- curl -Ls https://github.com/NebulousLabs/Sia/releases/download/v$SIA_VERSION/Sia-v$SIA_VERSION-darwin-amd64.zip
  -o build/sia/Sia-v$SIA_VERSION-darwin-amd64.zip
- curl -Ls https://github.com/NebulousLabs/Sia/releases/download/v$SIA_VERSION/Sia-v$SIA_VERSION-linux-amd64.zip
  -o build/sia/Sia-v$SIA_VERSION-linux-amd64.zip
- curl -Ls https://github.com/NebulousLabs/Sia/releases/download/v$SIA_VERSION/Sia-v$SIA_VERSION-windows-amd64.zip
  -o build/sia/Sia-v$SIA_VERSION-windows-amd64.zip
- "(cd build/sia && unzip Sia-v$SIA_VERSION-darwin-amd64.zip)"
- "(cd build/sia && unzip Sia-v$SIA_VERSION-linux-amd64.zip)"
- "(cd build/sia && unzip Sia-v$SIA_VERSION-windows-amd64.zip)"
- gradle distTar -x sia-linux -x sia-mac -x sia-win64
deploy:
  provider: releases
  api_key:
    secure: bu664xqdPaj+6JomOZJ7ivzIaDrGZXySCApcAYO7AIwBY0KlkbFO/zY/kYb7XRu7DfNYqDM9i2gGsdqneTDlvjg8NmxkpviKjrPMG8Fp8sjQK544ae4kpptMFc9d0eC+z5lv1WjrK9Jzq7Mnv0SKAcdtGguoGkUN1xE3PqK3wmvz7xKSAWSZZM3e5lw9AbBgShQTBfAV3qkE06Ga34Al72mqJ7BS3ZscxnJiLMW+jhlAGE+t+GybE53+QLgMJje2RU6gRJagi+IIem93uQuGAdZ6+eYrd4yqxEQyZpBIQz9kJs6P+WqC4yk46cmEBUZEYA/U8vxPOd7e8UawtOSfBMODvJKLAZoB/GKWXm9u0i0C906DEBZPSMMTVe3Pq1pO4smqiv8aC5cTCxsM3MXqsl1yssnhFX/HDJgu+QAqEoXmXNLUF4OV/1tIdveJXXjvGHOGUhTbC65d0qHA7alSUhql/IQ9Ha7QtSMFKVf3Re8U2IWr9VYfOhgGDw9e3cdARkDwZo+xk7moIfr4XGUMpOWRowZ+i0jZK2rE720T6TvsTjW95G9lXiUkViVex+vbiv/CwXak/msG5P/mkPxu8DACRltdquqAyyVZTZL94HOaL8Ra4g8GjyNOWmQujv4GgPltd0ZjCoEZh6IQ/qiyozRtonLgEwRMNzs7+wz5JOE=
  skip_cleanup: true
  file:
  - build/distributions/goobox-sync-sia-0.2.5-linux.tar.gz
  - build/distributions/goobox-sync-sia-0.2.5-mac.tar.gz
  - build/distributions/goobox-sync-sia-0.2.5-win64.tar.gz
  on:
    tags: true
    repo: GooBox/goobox-sync-sia
notifications:
  slack:
    secure: V8R+rm4EQaD8ph6efPLxFe6AscdvVLoo/fo9P2qrT32UGxCUPjKOXB2E5D73PEA1iuXShNqZmnqSG2N/t7Gf/JhKGfknwhxMCAWUV+ODb7VuEoKkp0OJCRYLH42k4rU3Vf6npNsd6BFz6HDUjmxaONKt4KMDpC5nArRWXaK1xFE2gllUzTnu8GSEzYmSzf4RRPWK7ajgI9DRerbu20+hnZKuH9/AFxT4GwqkyodpO8gYG3zRDiwaf3eoDbWPUus0qMqd983NaLk3iil8CaacrT7FNM7WNKzGmx5My4B5620k5EPzwso9L/kXbKnTAuSrNGw3H7UaT1ofzYbg8nqXqVuvbTho37630yna3R+8oO8WcwJ79WzNB/bguL8d91xTd3yUnSUjMYCgcpwa5ld16aN6uuufypeGjaLRq+5t35o/G0sRF1N+ZTdRDS5Pew3/uspChrQu6MVV51YSx82b0/4oQiZEWDJHE7JWprMlUj0Lj1ghca2X3p9KTFfPLxJ++IoBFa2Bx7/4jK/1TViFmNiMlgyOBnZ8aoAABeKcnh4TKPeT/hTqcqKmenUPBc0cY8ZjhTzODXgfr505Th12kod2LiVSlr732Y65ihUd0WPpoHzl/YY2kAndKeLLINwvakxGAQgIWNq/VhlUAHGB7yompo7dj1wbCFOKyNK0W0M=
