build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --no-daemon

test_script:
  - gradlew.bat test --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true