/*
 * Sia
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.goobox.sync.sia.client.api;

import io.goobox.sync.sia.client.ApiException;
import io.goobox.sync.sia.client.api.model.InlineResponse2007;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for MinerApi
 */
@Ignore
public class MinerApiTest {

    private final MinerApi api = new MinerApi();


    /**
     * returns the status of the miner.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void minerGetTest() throws ApiException {
        InlineResponse2007 response = api.minerGet();

        // TODO: test validations
    }

    /**
     * provides a block header that is ready to be grinded on for work.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void minerHeaderGetTest() throws ApiException {
        api.minerHeaderGet();

        // TODO: test validations
    }

    /**
     * submits a header that has passed the POW.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void minerHeaderPostTest() throws ApiException {
        api.minerHeaderPost();

        // TODO: test validations
    }

    /**
     * starts a single threaded cpu miner. Does nothing if the cpu miner is already running.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void minerStartGetTest() throws ApiException {
        api.minerStartGet();

        // TODO: test validations
    }

    /**
     * stops the cpu miner. Does nothing if the cpu miner is not running.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void minerStopGetTest() throws ApiException {
        api.minerStopGet();

        // TODO: test validations
    }

}
