/*
 * Sia
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.goobox.sync.sia.client.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse2009Contracts
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T13:36:31.527-05:00")
public class InlineResponse2009Contracts {
  @SerializedName("endheight")
  private Long endheight = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("netaddress")
  private String netaddress = null;

  @SerializedName("lasttransaction")
  private Object lasttransaction = null;

  @SerializedName("renterfunds")
  private String renterfunds = null;

  @SerializedName("size")
  private Long size = null;

  public InlineResponse2009Contracts endheight(Long endheight) {
    this.endheight = endheight;
    return this;
  }

   /**
   * Block height that the file contract ends on.
   * @return endheight
  **/
  @ApiModelProperty(example = "50000", value = "Block height that the file contract ends on.")
  public Long getEndheight() {
    return endheight;
  }

  public void setEndheight(Long endheight) {
    this.endheight = endheight;
  }

  public InlineResponse2009Contracts id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the file contract
   * @return id
  **/
  @ApiModelProperty(example = "1234567890abcdef0123456789abcdef0123456789abcdef0123456789abcdef", value = "ID of the file contract")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InlineResponse2009Contracts netaddress(String netaddress) {
    this.netaddress = netaddress;
    return this;
  }

   /**
   * Address of the host the file contract was formed with.
   * @return netaddress
  **/
  @ApiModelProperty(example = "12.34.56.78:9", value = "Address of the host the file contract was formed with.")
  public String getNetaddress() {
    return netaddress;
  }

  public void setNetaddress(String netaddress) {
    this.netaddress = netaddress;
  }

  public InlineResponse2009Contracts lasttransaction(Object lasttransaction) {
    this.lasttransaction = lasttransaction;
    return this;
  }

   /**
   * A signed transaction containing the most recent contract revision.
   * @return lasttransaction
  **/
  @ApiModelProperty(value = "A signed transaction containing the most recent contract revision.")
  public Object getLasttransaction() {
    return lasttransaction;
  }

  public void setLasttransaction(Object lasttransaction) {
    this.lasttransaction = lasttransaction;
  }

  public InlineResponse2009Contracts renterfunds(String renterfunds) {
    this.renterfunds = renterfunds;
    return this;
  }

   /**
   * Remaining funds left for the renter to spend on uploads &amp; downloads.
   * @return renterfunds
  **/
  @ApiModelProperty(example = "1234", value = "Remaining funds left for the renter to spend on uploads & downloads.")
  public String getRenterfunds() {
    return renterfunds;
  }

  public void setRenterfunds(String renterfunds) {
    this.renterfunds = renterfunds;
  }

  public InlineResponse2009Contracts size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * Size of the file contract, which is typically equal to the number of bytes that have been uploaded to the host.
   * @return size
  **/
  @ApiModelProperty(example = "8192", value = "Size of the file contract, which is typically equal to the number of bytes that have been uploaded to the host.")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2009Contracts inlineResponse2009Contracts = (InlineResponse2009Contracts) o;
    return Objects.equals(this.endheight, inlineResponse2009Contracts.endheight) &&
        Objects.equals(this.id, inlineResponse2009Contracts.id) &&
        Objects.equals(this.netaddress, inlineResponse2009Contracts.netaddress) &&
        Objects.equals(this.lasttransaction, inlineResponse2009Contracts.lasttransaction) &&
        Objects.equals(this.renterfunds, inlineResponse2009Contracts.renterfunds) &&
        Objects.equals(this.size, inlineResponse2009Contracts.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endheight, id, netaddress, lasttransaction, renterfunds, size);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2009Contracts {\n");
    
    sb.append("    endheight: ").append(toIndentedString(endheight)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    netaddress: ").append(toIndentedString(netaddress)).append("\n");
    sb.append("    lasttransaction: ").append(toIndentedString(lasttransaction)).append("\n");
    sb.append("    renterfunds: ").append(toIndentedString(renterfunds)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

