/*
 * Sia
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.goobox.sync.sia.client.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-01T00:02:50.340-05:00")
public class InlineResponse200 {
  @SerializedName("currentblock")
  private String currentblock = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("synced")
  private Boolean synced = null;

  public InlineResponse200 currentblock(String currentblock) {
    this.currentblock = currentblock;
    return this;
  }

   /**
   * Get currentblock
   * @return currentblock
  **/
  @ApiModelProperty(value = "")
  public String getCurrentblock() {
    return currentblock;
  }

  public void setCurrentblock(String currentblock) {
    this.currentblock = currentblock;
  }

  public InlineResponse200 height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Number of blocks preceding the current block.
   * @return height
  **/
  @ApiModelProperty(example = "62248", value = "Number of blocks preceding the current block.")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public InlineResponse200 synced(Boolean synced) {
    this.synced = synced;
    return this;
  }

   /**
   * True if the consensus set is synced with the network, i.e. it has downloaded the entire blockchain.
   * @return synced
  **/
  @ApiModelProperty(value = "True if the consensus set is synced with the network, i.e. it has downloaded the entire blockchain.")
  public Boolean isSynced() {
    return synced;
  }

  public void setSynced(Boolean synced) {
    this.synced = synced;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.currentblock, inlineResponse200.currentblock) &&
        Objects.equals(this.height, inlineResponse200.height) &&
        Objects.equals(this.synced, inlineResponse200.synced);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentblock, height, synced);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    currentblock: ").append(toIndentedString(currentblock)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    synced: ").append(toIndentedString(synced)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

