/*
 * Sia
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.goobox.sync.sia.client.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.goobox.sync.sia.client.api.model.InlineResponse2004Externalsettings;
import io.goobox.sync.sia.client.api.model.InlineResponse2004Financialmetrics;
import io.goobox.sync.sia.client.api.model.InlineResponse2004Internalsettings;
import io.goobox.sync.sia.client.api.model.InlineResponse2004Networkmetrics;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse2004
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-01T00:02:50.340-05:00")
public class InlineResponse2004 {
  @SerializedName("connectabilitystatus")
  private String connectabilitystatus = null;

  @SerializedName("externalsettings")
  private InlineResponse2004Externalsettings externalsettings = null;

  @SerializedName("financialmetrics")
  private InlineResponse2004Financialmetrics financialmetrics = null;

  @SerializedName("internalsettings")
  private InlineResponse2004Internalsettings internalsettings = null;

  @SerializedName("networkmetrics")
  private InlineResponse2004Networkmetrics networkmetrics = null;

  @SerializedName("workingstatus")
  private String workingstatus = null;

  public InlineResponse2004 connectabilitystatus(String connectabilitystatus) {
    this.connectabilitystatus = connectabilitystatus;
    return this;
  }

   /**
   * connectabilitystatus is one of \&quot;checking\&quot;, \&quot;connectable\&quot;, or \&quot;not connectable\&quot;, and indicates if the host can connect to itself on its configured NetAddress. 
   * @return connectabilitystatus
  **/
  @ApiModelProperty(example = "checking", value = "connectabilitystatus is one of \"checking\", \"connectable\", or \"not connectable\", and indicates if the host can connect to itself on its configured NetAddress. ")
  public String getConnectabilitystatus() {
    return connectabilitystatus;
  }

  public void setConnectabilitystatus(String connectabilitystatus) {
    this.connectabilitystatus = connectabilitystatus;
  }

  public InlineResponse2004 externalsettings(InlineResponse2004Externalsettings externalsettings) {
    this.externalsettings = externalsettings;
    return this;
  }

   /**
   * Get externalsettings
   * @return externalsettings
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2004Externalsettings getExternalsettings() {
    return externalsettings;
  }

  public void setExternalsettings(InlineResponse2004Externalsettings externalsettings) {
    this.externalsettings = externalsettings;
  }

  public InlineResponse2004 financialmetrics(InlineResponse2004Financialmetrics financialmetrics) {
    this.financialmetrics = financialmetrics;
    return this;
  }

   /**
   * Get financialmetrics
   * @return financialmetrics
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2004Financialmetrics getFinancialmetrics() {
    return financialmetrics;
  }

  public void setFinancialmetrics(InlineResponse2004Financialmetrics financialmetrics) {
    this.financialmetrics = financialmetrics;
  }

  public InlineResponse2004 internalsettings(InlineResponse2004Internalsettings internalsettings) {
    this.internalsettings = internalsettings;
    return this;
  }

   /**
   * Get internalsettings
   * @return internalsettings
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2004Internalsettings getInternalsettings() {
    return internalsettings;
  }

  public void setInternalsettings(InlineResponse2004Internalsettings internalsettings) {
    this.internalsettings = internalsettings;
  }

  public InlineResponse2004 networkmetrics(InlineResponse2004Networkmetrics networkmetrics) {
    this.networkmetrics = networkmetrics;
    return this;
  }

   /**
   * Get networkmetrics
   * @return networkmetrics
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2004Networkmetrics getNetworkmetrics() {
    return networkmetrics;
  }

  public void setNetworkmetrics(InlineResponse2004Networkmetrics networkmetrics) {
    this.networkmetrics = networkmetrics;
  }

  public InlineResponse2004 workingstatus(String workingstatus) {
    this.workingstatus = workingstatus;
    return this;
  }

   /**
   * workingstatus is one of \&quot;checking\&quot;, \&quot;working\&quot;, or \&quot;not working\&quot; and indicates if the host is being actively used by renters. 
   * @return workingstatus
  **/
  @ApiModelProperty(example = "checking", value = "workingstatus is one of \"checking\", \"working\", or \"not working\" and indicates if the host is being actively used by renters. ")
  public String getWorkingstatus() {
    return workingstatus;
  }

  public void setWorkingstatus(String workingstatus) {
    this.workingstatus = workingstatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return Objects.equals(this.connectabilitystatus, inlineResponse2004.connectabilitystatus) &&
        Objects.equals(this.externalsettings, inlineResponse2004.externalsettings) &&
        Objects.equals(this.financialmetrics, inlineResponse2004.financialmetrics) &&
        Objects.equals(this.internalsettings, inlineResponse2004.internalsettings) &&
        Objects.equals(this.networkmetrics, inlineResponse2004.networkmetrics) &&
        Objects.equals(this.workingstatus, inlineResponse2004.workingstatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectabilitystatus, externalsettings, financialmetrics, internalsettings, networkmetrics, workingstatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("    connectabilitystatus: ").append(toIndentedString(connectabilitystatus)).append("\n");
    sb.append("    externalsettings: ").append(toIndentedString(externalsettings)).append("\n");
    sb.append("    financialmetrics: ").append(toIndentedString(financialmetrics)).append("\n");
    sb.append("    internalsettings: ").append(toIndentedString(internalsettings)).append("\n");
    sb.append("    networkmetrics: ").append(toIndentedString(networkmetrics)).append("\n");
    sb.append("    workingstatus: ").append(toIndentedString(workingstatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

