/*
 * Sia
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.goobox.sync.sia.client.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.goobox.sync.sia.client.api.model.InlineResponse200Externalsettings;
import io.goobox.sync.sia.client.api.model.InlineResponse200Financialmetrics;
import io.goobox.sync.sia.client.api.model.InlineResponse200Internalsettings;
import io.goobox.sync.sia.client.api.model.InlineResponse200Networkmetrics;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-17T14:17:27.462-05:00")
public class InlineResponse200 {
  @SerializedName("externalsettings")
  private InlineResponse200Externalsettings externalsettings = null;

  @SerializedName("financialmetrics")
  private InlineResponse200Financialmetrics financialmetrics = null;

  @SerializedName("internalsettings")
  private InlineResponse200Internalsettings internalsettings = null;

  @SerializedName("networkmetrics")
  private InlineResponse200Networkmetrics networkmetrics = null;

  @SerializedName("connectabilitystatus")
  private String connectabilitystatus = null;

  @SerializedName("workingstatus")
  private String workingstatus = null;

  public InlineResponse200 externalsettings(InlineResponse200Externalsettings externalsettings) {
    this.externalsettings = externalsettings;
    return this;
  }

   /**
   * Get externalsettings
   * @return externalsettings
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200Externalsettings getExternalsettings() {
    return externalsettings;
  }

  public void setExternalsettings(InlineResponse200Externalsettings externalsettings) {
    this.externalsettings = externalsettings;
  }

  public InlineResponse200 financialmetrics(InlineResponse200Financialmetrics financialmetrics) {
    this.financialmetrics = financialmetrics;
    return this;
  }

   /**
   * Get financialmetrics
   * @return financialmetrics
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200Financialmetrics getFinancialmetrics() {
    return financialmetrics;
  }

  public void setFinancialmetrics(InlineResponse200Financialmetrics financialmetrics) {
    this.financialmetrics = financialmetrics;
  }

  public InlineResponse200 internalsettings(InlineResponse200Internalsettings internalsettings) {
    this.internalsettings = internalsettings;
    return this;
  }

   /**
   * Get internalsettings
   * @return internalsettings
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200Internalsettings getInternalsettings() {
    return internalsettings;
  }

  public void setInternalsettings(InlineResponse200Internalsettings internalsettings) {
    this.internalsettings = internalsettings;
  }

  public InlineResponse200 networkmetrics(InlineResponse200Networkmetrics networkmetrics) {
    this.networkmetrics = networkmetrics;
    return this;
  }

   /**
   * Get networkmetrics
   * @return networkmetrics
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200Networkmetrics getNetworkmetrics() {
    return networkmetrics;
  }

  public void setNetworkmetrics(InlineResponse200Networkmetrics networkmetrics) {
    this.networkmetrics = networkmetrics;
  }

  public InlineResponse200 connectabilitystatus(String connectabilitystatus) {
    this.connectabilitystatus = connectabilitystatus;
    return this;
  }

   /**
   * connectabilitystatus is one of \&quot;checking\&quot;, \&quot;connectable\&quot;, or \&quot;not connectable\&quot;, and indicates if the host can connect to itself on its configured NetAddress. 
   * @return connectabilitystatus
  **/
  @ApiModelProperty(example = "checking", value = "connectabilitystatus is one of \"checking\", \"connectable\", or \"not connectable\", and indicates if the host can connect to itself on its configured NetAddress. ")
  public String getConnectabilitystatus() {
    return connectabilitystatus;
  }

  public void setConnectabilitystatus(String connectabilitystatus) {
    this.connectabilitystatus = connectabilitystatus;
  }

  public InlineResponse200 workingstatus(String workingstatus) {
    this.workingstatus = workingstatus;
    return this;
  }

   /**
   * workingstatus is one of \&quot;checking\&quot;, \&quot;working\&quot;, or \&quot;not working\&quot; and indicates if the host is being actively used by renters. 
   * @return workingstatus
  **/
  @ApiModelProperty(example = "checking", value = "workingstatus is one of \"checking\", \"working\", or \"not working\" and indicates if the host is being actively used by renters. ")
  public String getWorkingstatus() {
    return workingstatus;
  }

  public void setWorkingstatus(String workingstatus) {
    this.workingstatus = workingstatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.externalsettings, inlineResponse200.externalsettings) &&
        Objects.equals(this.financialmetrics, inlineResponse200.financialmetrics) &&
        Objects.equals(this.internalsettings, inlineResponse200.internalsettings) &&
        Objects.equals(this.networkmetrics, inlineResponse200.networkmetrics) &&
        Objects.equals(this.connectabilitystatus, inlineResponse200.connectabilitystatus) &&
        Objects.equals(this.workingstatus, inlineResponse200.workingstatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalsettings, financialmetrics, internalsettings, networkmetrics, connectabilitystatus, workingstatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    externalsettings: ").append(toIndentedString(externalsettings)).append("\n");
    sb.append("    financialmetrics: ").append(toIndentedString(financialmetrics)).append("\n");
    sb.append("    internalsettings: ").append(toIndentedString(internalsettings)).append("\n");
    sb.append("    networkmetrics: ").append(toIndentedString(networkmetrics)).append("\n");
    sb.append("    connectabilitystatus: ").append(toIndentedString(connectabilitystatus)).append("\n");
    sb.append("    workingstatus: ").append(toIndentedString(workingstatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

