/*
 * Sia
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.goobox.sync.sia.client.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse20010Downloads
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-01T00:02:50.340-05:00")
public class InlineResponse20010Downloads {
  @SerializedName("completed")
  private Boolean completed = null;

  @SerializedName("destination")
  private String destination = null;

  @SerializedName("destinationtype")
  private String destinationtype = null;

  @SerializedName("endtime")
  private String endtime = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("length")
  private Long length = null;

  @SerializedName("offset")
  private Long offset = null;

  @SerializedName("received")
  private Long received = null;

  @SerializedName("siapath")
  private String siapath = null;

  @SerializedName("starttime")
  private String starttime = null;

  @SerializedName("totaldatatransfered")
  private Long totaldatatransfered = null;

  public InlineResponse20010Downloads completed(Boolean completed) {
    this.completed = completed;
    return this;
  }

   /**
   * Whether or not the download has completed. Will be false initially, and set to true immediately as the download has been fully written out to the file, to the http stream, or to the in-memory buffer. Completed will also be set to true if there is an error that causes the download to fail.
   * @return completed
  **/
  @ApiModelProperty(example = "true", value = "Whether or not the download has completed. Will be false initially, and set to true immediately as the download has been fully written out to the file, to the http stream, or to the in-memory buffer. Completed will also be set to true if there is an error that causes the download to fail.")
  public Boolean isCompleted() {
    return completed;
  }

  public void setCompleted(Boolean completed) {
    this.completed = completed;
  }

  public InlineResponse20010Downloads destination(String destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Local path that the file will be downloaded to.
   * @return destination
  **/
  @ApiModelProperty(example = "/home/users/alice", value = "Local path that the file will be downloaded to.")
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }

  public InlineResponse20010Downloads destinationtype(String destinationtype) {
    this.destinationtype = destinationtype;
    return this;
  }

   /**
   * What type of destination was used. Can be \&quot;file\&quot;, indicating a download to disk, can be \&quot;buffer\&quot;, indicating a download to memory, and can be \&quot;http stream\&quot;, indicating that the download was streamed through the http API.
   * @return destinationtype
  **/
  @ApiModelProperty(example = "file", value = "What type of destination was used. Can be \"file\", indicating a download to disk, can be \"buffer\", indicating a download to memory, and can be \"http stream\", indicating that the download was streamed through the http API.")
  public String getDestinationtype() {
    return destinationtype;
  }

  public void setDestinationtype(String destinationtype) {
    this.destinationtype = destinationtype;
  }

  public InlineResponse20010Downloads endtime(String endtime) {
    this.endtime = endtime;
    return this;
  }

   /**
   * Time at which the download completed in RFC 3339 time. Will be zero if the download has not yet completed.
   * @return endtime
  **/
  @ApiModelProperty(example = "2009-11-10T23:00:00Z", value = "Time at which the download completed in RFC 3339 time. Will be zero if the download has not yet completed.")
  public String getEndtime() {
    return endtime;
  }

  public void setEndtime(String endtime) {
    this.endtime = endtime;
  }

  public InlineResponse20010Downloads error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Error encountered while downloading. If there was no error (yet), it will be the empty string.
   * @return error
  **/
  @ApiModelProperty(example = "", value = "Error encountered while downloading. If there was no error (yet), it will be the empty string.")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public InlineResponse20010Downloads length(Long length) {
    this.length = length;
    return this;
  }

   /**
   * Length of the download. If the download was a partial download, this will indicate the length of the partial download, and not the length of the full file.
   * @return length
  **/
  @ApiModelProperty(example = "8192", value = "Length of the download. If the download was a partial download, this will indicate the length of the partial download, and not the length of the full file.")
  public Long getLength() {
    return length;
  }

  public void setLength(Long length) {
    this.length = length;
  }

  public InlineResponse20010Downloads offset(Long offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Offset within the file of the download. For full file downloads, the offset will be &#39;0&#39;. For partial downloads, the offset may be anywhere within the file. offset+length will never exceed the full file size.
   * @return offset
  **/
  @ApiModelProperty(example = "0", value = "Offset within the file of the download. For full file downloads, the offset will be '0'. For partial downloads, the offset may be anywhere within the file. offset+length will never exceed the full file size.")
  public Long getOffset() {
    return offset;
  }

  public void setOffset(Long offset) {
    this.offset = offset;
  }

  public InlineResponse20010Downloads received(Long received) {
    this.received = received;
    return this;
  }

   /**
   * Number of bytes downloaded thus far. Will only be updated as segments of the file complete fully. This typically has a resolution of tens of megabytes.
   * @return received
  **/
  @ApiModelProperty(example = "4096", value = "Number of bytes downloaded thus far. Will only be updated as segments of the file complete fully. This typically has a resolution of tens of megabytes.")
  public Long getReceived() {
    return received;
  }

  public void setReceived(Long received) {
    this.received = received;
  }

  public InlineResponse20010Downloads siapath(String siapath) {
    this.siapath = siapath;
    return this;
  }

   /**
   * Siapath given to the file when it was uploaded.
   * @return siapath
  **/
  @ApiModelProperty(example = "foo/bar.txt", value = "Siapath given to the file when it was uploaded.")
  public String getSiapath() {
    return siapath;
  }

  public void setSiapath(String siapath) {
    this.siapath = siapath;
  }

  public InlineResponse20010Downloads starttime(String starttime) {
    this.starttime = starttime;
    return this;
  }

   /**
   * Time at which the download was initiated in RFC 3339.
   * @return starttime
  **/
  @ApiModelProperty(example = "2009-11-10T23:00:00Z", value = "Time at which the download was initiated in RFC 3339.")
  public String getStarttime() {
    return starttime;
  }

  public void setStarttime(String starttime) {
    this.starttime = starttime;
  }

  public InlineResponse20010Downloads totaldatatransfered(Long totaldatatransfered) {
    this.totaldatatransfered = totaldatatransfered;
    return this;
  }

   /**
   * The total amount of data transfered when downloading the file. This will eventually include data transferred during contract + payment negotiation, as well as data from failed piece downloads.
   * @return totaldatatransfered
  **/
  @ApiModelProperty(example = "10321", value = "The total amount of data transfered when downloading the file. This will eventually include data transferred during contract + payment negotiation, as well as data from failed piece downloads.")
  public Long getTotaldatatransfered() {
    return totaldatatransfered;
  }

  public void setTotaldatatransfered(Long totaldatatransfered) {
    this.totaldatatransfered = totaldatatransfered;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010Downloads inlineResponse20010Downloads = (InlineResponse20010Downloads) o;
    return Objects.equals(this.completed, inlineResponse20010Downloads.completed) &&
        Objects.equals(this.destination, inlineResponse20010Downloads.destination) &&
        Objects.equals(this.destinationtype, inlineResponse20010Downloads.destinationtype) &&
        Objects.equals(this.endtime, inlineResponse20010Downloads.endtime) &&
        Objects.equals(this.error, inlineResponse20010Downloads.error) &&
        Objects.equals(this.length, inlineResponse20010Downloads.length) &&
        Objects.equals(this.offset, inlineResponse20010Downloads.offset) &&
        Objects.equals(this.received, inlineResponse20010Downloads.received) &&
        Objects.equals(this.siapath, inlineResponse20010Downloads.siapath) &&
        Objects.equals(this.starttime, inlineResponse20010Downloads.starttime) &&
        Objects.equals(this.totaldatatransfered, inlineResponse20010Downloads.totaldatatransfered);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completed, destination, destinationtype, endtime, error, length, offset, received, siapath, starttime, totaldatatransfered);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010Downloads {\n");
    
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    destinationtype: ").append(toIndentedString(destinationtype)).append("\n");
    sb.append("    endtime: ").append(toIndentedString(endtime)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    received: ").append(toIndentedString(received)).append("\n");
    sb.append("    siapath: ").append(toIndentedString(siapath)).append("\n");
    sb.append("    starttime: ").append(toIndentedString(starttime)).append("\n");
    sb.append("    totaldatatransfered: ").append(toIndentedString(totaldatatransfered)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

