/*
 * Sia
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.goobox.sync.sia.client.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.goobox.sync.sia.client.api.model.InlineResponse2007Peers;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2007
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-17T14:17:27.462-05:00")
public class InlineResponse2007 {
  @SerializedName("netaddress")
  private String netaddress = null;

  @SerializedName("peers")
  private List<InlineResponse2007Peers> peers = null;

  public InlineResponse2007 netaddress(String netaddress) {
    this.netaddress = netaddress;
    return this;
  }

   /**
   * netaddress is the network address of the gateway as seen by the rest of the network. The address consists of the external IP address and the port Sia is listening on. It represents a &#x60;modules.NetAddress&#x60;. 
   * @return netaddress
  **/
  @ApiModelProperty(value = "netaddress is the network address of the gateway as seen by the rest of the network. The address consists of the external IP address and the port Sia is listening on. It represents a `modules.NetAddress`. ")
  public String getNetaddress() {
    return netaddress;
  }

  public void setNetaddress(String netaddress) {
    this.netaddress = netaddress;
  }

  public InlineResponse2007 peers(List<InlineResponse2007Peers> peers) {
    this.peers = peers;
    return this;
  }

  public InlineResponse2007 addPeersItem(InlineResponse2007Peers peersItem) {
    if (this.peers == null) {
      this.peers = new ArrayList<InlineResponse2007Peers>();
    }
    this.peers.add(peersItem);
    return this;
  }

   /**
   * peers is an array of peers the gateway is connected to. It represents an array of &#x60;modules.Peer&#x60;s.
   * @return peers
  **/
  @ApiModelProperty(value = "peers is an array of peers the gateway is connected to. It represents an array of `modules.Peer`s.")
  public List<InlineResponse2007Peers> getPeers() {
    return peers;
  }

  public void setPeers(List<InlineResponse2007Peers> peers) {
    this.peers = peers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007 inlineResponse2007 = (InlineResponse2007) o;
    return Objects.equals(this.netaddress, inlineResponse2007.netaddress) &&
        Objects.equals(this.peers, inlineResponse2007.peers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(netaddress, peers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007 {\n");
    
    sb.append("    netaddress: ").append(toIndentedString(netaddress)).append("\n");
    sb.append("    peers: ").append(toIndentedString(peers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

