/*
 * Sia
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.goobox.sync.sia.client.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The financial status of the host.
 */
@ApiModel(description = "The financial status of the host.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-23T01:54:58.054-05:00")
public class InlineResponse200Financialmetrics {
  @SerializedName("contractcount")
  private Integer contractcount = null;

  @SerializedName("contractcompensation")
  private String contractcompensation = null;

  @SerializedName("potentialcontractcompensation")
  private String potentialcontractcompensation = null;

  @SerializedName("lockedstoragecollateral")
  private String lockedstoragecollateral = null;

  @SerializedName("lostrevenue")
  private String lostrevenue = null;

  @SerializedName("loststoragecollateral")
  private String loststoragecollateral = null;

  @SerializedName("potentialstoragerevenue")
  private String potentialstoragerevenue = null;

  @SerializedName("riskedstoragecollateral")
  private String riskedstoragecollateral = null;

  @SerializedName("storagerevenue")
  private String storagerevenue = null;

  @SerializedName("transactionfeeexpenses")
  private String transactionfeeexpenses = null;

  @SerializedName("downloadbandwidthrevenue")
  private String downloadbandwidthrevenue = null;

  @SerializedName("potentialdownloadbandwidthrevenue")
  private String potentialdownloadbandwidthrevenue = null;

  @SerializedName("potentialuploadbandwidthrevenue")
  private String potentialuploadbandwidthrevenue = null;

  @SerializedName("uploadbandwidthrevenue")
  private String uploadbandwidthrevenue = null;

  public InlineResponse200Financialmetrics contractcount(Integer contractcount) {
    this.contractcount = contractcount;
    return this;
  }

   /**
   * Number of open file contracts.
   * @return contractcount
  **/
  @ApiModelProperty(example = "2", value = "Number of open file contracts.")
  public Integer getContractcount() {
    return contractcount;
  }

  public void setContractcount(Integer contractcount) {
    this.contractcount = contractcount;
  }

  public InlineResponse200Financialmetrics contractcompensation(String contractcompensation) {
    this.contractcompensation = contractcompensation;
    return this;
  }

   /**
   * The amount of money that renters have given to the host to pay for file contracts. The host is required to submit a file contract revision and a storage proof for every file contract that gets created, and the renter pays for the miner fees on these objects. 
   * @return contractcompensation
  **/
  @ApiModelProperty(example = "123", value = "The amount of money that renters have given to the host to pay for file contracts. The host is required to submit a file contract revision and a storage proof for every file contract that gets created, and the renter pays for the miner fees on these objects. ")
  public String getContractcompensation() {
    return contractcompensation;
  }

  public void setContractcompensation(String contractcompensation) {
    this.contractcompensation = contractcompensation;
  }

  public InlineResponse200Financialmetrics potentialcontractcompensation(String potentialcontractcompensation) {
    this.potentialcontractcompensation = potentialcontractcompensation;
    return this;
  }

   /**
   * The amount of money that renters have given to the host to pay for file contracts which have not been confirmed yet. The potential compensation becomes compensation after the storage proof is submitted. 
   * @return potentialcontractcompensation
  **/
  @ApiModelProperty(example = "123", value = "The amount of money that renters have given to the host to pay for file contracts which have not been confirmed yet. The potential compensation becomes compensation after the storage proof is submitted. ")
  public String getPotentialcontractcompensation() {
    return potentialcontractcompensation;
  }

  public void setPotentialcontractcompensation(String potentialcontractcompensation) {
    this.potentialcontractcompensation = potentialcontractcompensation;
  }

  public InlineResponse200Financialmetrics lockedstoragecollateral(String lockedstoragecollateral) {
    this.lockedstoragecollateral = lockedstoragecollateral;
    return this;
  }

   /**
   * The amount of storage collateral which the host has tied up in file contracts. The host has to commit collateral to a file contract even if there is no storage, but the locked collateral will be returned even if the host does not submit a storage proof - the collateral is not at risk, it is merely set aside so that it can be put at risk later. 
   * @return lockedstoragecollateral
  **/
  @ApiModelProperty(example = "123", value = "The amount of storage collateral which the host has tied up in file contracts. The host has to commit collateral to a file contract even if there is no storage, but the locked collateral will be returned even if the host does not submit a storage proof - the collateral is not at risk, it is merely set aside so that it can be put at risk later. ")
  public String getLockedstoragecollateral() {
    return lockedstoragecollateral;
  }

  public void setLockedstoragecollateral(String lockedstoragecollateral) {
    this.lockedstoragecollateral = lockedstoragecollateral;
  }

  public InlineResponse200Financialmetrics lostrevenue(String lostrevenue) {
    this.lostrevenue = lostrevenue;
    return this;
  }

   /**
   * The amount of revenue, including storage revenue and bandwidth revenue, that has been lost due to failed file contracts and failed storage proofs. 
   * @return lostrevenue
  **/
  @ApiModelProperty(example = "123", value = "The amount of revenue, including storage revenue and bandwidth revenue, that has been lost due to failed file contracts and failed storage proofs. ")
  public String getLostrevenue() {
    return lostrevenue;
  }

  public void setLostrevenue(String lostrevenue) {
    this.lostrevenue = lostrevenue;
  }

  public InlineResponse200Financialmetrics loststoragecollateral(String loststoragecollateral) {
    this.loststoragecollateral = loststoragecollateral;
    return this;
  }

   /**
   * The amount of collateral that was put up to protect data which has been lost due to failed file contracts and missed storage proofs.
   * @return loststoragecollateral
  **/
  @ApiModelProperty(example = "123", value = "The amount of collateral that was put up to protect data which has been lost due to failed file contracts and missed storage proofs.")
  public String getLoststoragecollateral() {
    return loststoragecollateral;
  }

  public void setLoststoragecollateral(String loststoragecollateral) {
    this.loststoragecollateral = loststoragecollateral;
  }

  public InlineResponse200Financialmetrics potentialstoragerevenue(String potentialstoragerevenue) {
    this.potentialstoragerevenue = potentialstoragerevenue;
    return this;
  }

   /**
   * The amount of revenue that the host stands to earn if all storage proofs are submitted corectly and in time.
   * @return potentialstoragerevenue
  **/
  @ApiModelProperty(example = "123", value = "The amount of revenue that the host stands to earn if all storage proofs are submitted corectly and in time.")
  public String getPotentialstoragerevenue() {
    return potentialstoragerevenue;
  }

  public void setPotentialstoragerevenue(String potentialstoragerevenue) {
    this.potentialstoragerevenue = potentialstoragerevenue;
  }

  public InlineResponse200Financialmetrics riskedstoragecollateral(String riskedstoragecollateral) {
    this.riskedstoragecollateral = riskedstoragecollateral;
    return this;
  }

   /**
   * The amount of money that the host has risked on file contracts. If the host starts missing storage proofs, the host can forfeit up to this many coins. In the event of a missed storage proof, locked storage collateral gets returned, but risked storage collateral does not get returned. 
   * @return riskedstoragecollateral
  **/
  @ApiModelProperty(example = "123", value = "The amount of money that the host has risked on file contracts. If the host starts missing storage proofs, the host can forfeit up to this many coins. In the event of a missed storage proof, locked storage collateral gets returned, but risked storage collateral does not get returned. ")
  public String getRiskedstoragecollateral() {
    return riskedstoragecollateral;
  }

  public void setRiskedstoragecollateral(String riskedstoragecollateral) {
    this.riskedstoragecollateral = riskedstoragecollateral;
  }

  public InlineResponse200Financialmetrics storagerevenue(String storagerevenue) {
    this.storagerevenue = storagerevenue;
    return this;
  }

   /**
   * The amount of money that the host has earned from storing data. This money has been locked down by successful storage proofs.
   * @return storagerevenue
  **/
  @ApiModelProperty(example = "123", value = "The amount of money that the host has earned from storing data. This money has been locked down by successful storage proofs.")
  public String getStoragerevenue() {
    return storagerevenue;
  }

  public void setStoragerevenue(String storagerevenue) {
    this.storagerevenue = storagerevenue;
  }

  public InlineResponse200Financialmetrics transactionfeeexpenses(String transactionfeeexpenses) {
    this.transactionfeeexpenses = transactionfeeexpenses;
    return this;
  }

   /**
   * The amount of money that the host has spent on transaction fees when submitting host announcements, file contract revisions, and storage proofs. 
   * @return transactionfeeexpenses
  **/
  @ApiModelProperty(example = "123", value = "The amount of money that the host has spent on transaction fees when submitting host announcements, file contract revisions, and storage proofs. ")
  public String getTransactionfeeexpenses() {
    return transactionfeeexpenses;
  }

  public void setTransactionfeeexpenses(String transactionfeeexpenses) {
    this.transactionfeeexpenses = transactionfeeexpenses;
  }

  public InlineResponse200Financialmetrics downloadbandwidthrevenue(String downloadbandwidthrevenue) {
    this.downloadbandwidthrevenue = downloadbandwidthrevenue;
    return this;
  }

   /**
   * The amount of money that the host has made from renters downloading their files. This money has been locked in by successsful storage proofs. 
   * @return downloadbandwidthrevenue
  **/
  @ApiModelProperty(example = "123", value = "The amount of money that the host has made from renters downloading their files. This money has been locked in by successsful storage proofs. ")
  public String getDownloadbandwidthrevenue() {
    return downloadbandwidthrevenue;
  }

  public void setDownloadbandwidthrevenue(String downloadbandwidthrevenue) {
    this.downloadbandwidthrevenue = downloadbandwidthrevenue;
  }

  public InlineResponse200Financialmetrics potentialdownloadbandwidthrevenue(String potentialdownloadbandwidthrevenue) {
    this.potentialdownloadbandwidthrevenue = potentialdownloadbandwidthrevenue;
    return this;
  }

   /**
   * The amount of money that the host stands to make from renters that downloaded their files. The host will only realize this revenue if the host successfully submits storage proofs for the related file contracts. 
   * @return potentialdownloadbandwidthrevenue
  **/
  @ApiModelProperty(example = "123", value = "The amount of money that the host stands to make from renters that downloaded their files. The host will only realize this revenue if the host successfully submits storage proofs for the related file contracts. ")
  public String getPotentialdownloadbandwidthrevenue() {
    return potentialdownloadbandwidthrevenue;
  }

  public void setPotentialdownloadbandwidthrevenue(String potentialdownloadbandwidthrevenue) {
    this.potentialdownloadbandwidthrevenue = potentialdownloadbandwidthrevenue;
  }

  public InlineResponse200Financialmetrics potentialuploadbandwidthrevenue(String potentialuploadbandwidthrevenue) {
    this.potentialuploadbandwidthrevenue = potentialuploadbandwidthrevenue;
    return this;
  }

   /**
   * The amount of money that the host stands to make from renters that uploaded files. The host will only realize this revenue if the host successfully submits storage proofs for the related file contracts. 
   * @return potentialuploadbandwidthrevenue
  **/
  @ApiModelProperty(example = "123", value = "The amount of money that the host stands to make from renters that uploaded files. The host will only realize this revenue if the host successfully submits storage proofs for the related file contracts. ")
  public String getPotentialuploadbandwidthrevenue() {
    return potentialuploadbandwidthrevenue;
  }

  public void setPotentialuploadbandwidthrevenue(String potentialuploadbandwidthrevenue) {
    this.potentialuploadbandwidthrevenue = potentialuploadbandwidthrevenue;
  }

  public InlineResponse200Financialmetrics uploadbandwidthrevenue(String uploadbandwidthrevenue) {
    this.uploadbandwidthrevenue = uploadbandwidthrevenue;
    return this;
  }

   /**
   * The amount of money that the host has made from renters uploading their files. This money has been locked in by successful storage proofs. 
   * @return uploadbandwidthrevenue
  **/
  @ApiModelProperty(example = "123", value = "The amount of money that the host has made from renters uploading their files. This money has been locked in by successful storage proofs. ")
  public String getUploadbandwidthrevenue() {
    return uploadbandwidthrevenue;
  }

  public void setUploadbandwidthrevenue(String uploadbandwidthrevenue) {
    this.uploadbandwidthrevenue = uploadbandwidthrevenue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200Financialmetrics inlineResponse200Financialmetrics = (InlineResponse200Financialmetrics) o;
    return Objects.equals(this.contractcount, inlineResponse200Financialmetrics.contractcount) &&
        Objects.equals(this.contractcompensation, inlineResponse200Financialmetrics.contractcompensation) &&
        Objects.equals(this.potentialcontractcompensation, inlineResponse200Financialmetrics.potentialcontractcompensation) &&
        Objects.equals(this.lockedstoragecollateral, inlineResponse200Financialmetrics.lockedstoragecollateral) &&
        Objects.equals(this.lostrevenue, inlineResponse200Financialmetrics.lostrevenue) &&
        Objects.equals(this.loststoragecollateral, inlineResponse200Financialmetrics.loststoragecollateral) &&
        Objects.equals(this.potentialstoragerevenue, inlineResponse200Financialmetrics.potentialstoragerevenue) &&
        Objects.equals(this.riskedstoragecollateral, inlineResponse200Financialmetrics.riskedstoragecollateral) &&
        Objects.equals(this.storagerevenue, inlineResponse200Financialmetrics.storagerevenue) &&
        Objects.equals(this.transactionfeeexpenses, inlineResponse200Financialmetrics.transactionfeeexpenses) &&
        Objects.equals(this.downloadbandwidthrevenue, inlineResponse200Financialmetrics.downloadbandwidthrevenue) &&
        Objects.equals(this.potentialdownloadbandwidthrevenue, inlineResponse200Financialmetrics.potentialdownloadbandwidthrevenue) &&
        Objects.equals(this.potentialuploadbandwidthrevenue, inlineResponse200Financialmetrics.potentialuploadbandwidthrevenue) &&
        Objects.equals(this.uploadbandwidthrevenue, inlineResponse200Financialmetrics.uploadbandwidthrevenue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractcount, contractcompensation, potentialcontractcompensation, lockedstoragecollateral, lostrevenue, loststoragecollateral, potentialstoragerevenue, riskedstoragecollateral, storagerevenue, transactionfeeexpenses, downloadbandwidthrevenue, potentialdownloadbandwidthrevenue, potentialuploadbandwidthrevenue, uploadbandwidthrevenue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200Financialmetrics {\n");
    
    sb.append("    contractcount: ").append(toIndentedString(contractcount)).append("\n");
    sb.append("    contractcompensation: ").append(toIndentedString(contractcompensation)).append("\n");
    sb.append("    potentialcontractcompensation: ").append(toIndentedString(potentialcontractcompensation)).append("\n");
    sb.append("    lockedstoragecollateral: ").append(toIndentedString(lockedstoragecollateral)).append("\n");
    sb.append("    lostrevenue: ").append(toIndentedString(lostrevenue)).append("\n");
    sb.append("    loststoragecollateral: ").append(toIndentedString(loststoragecollateral)).append("\n");
    sb.append("    potentialstoragerevenue: ").append(toIndentedString(potentialstoragerevenue)).append("\n");
    sb.append("    riskedstoragecollateral: ").append(toIndentedString(riskedstoragecollateral)).append("\n");
    sb.append("    storagerevenue: ").append(toIndentedString(storagerevenue)).append("\n");
    sb.append("    transactionfeeexpenses: ").append(toIndentedString(transactionfeeexpenses)).append("\n");
    sb.append("    downloadbandwidthrevenue: ").append(toIndentedString(downloadbandwidthrevenue)).append("\n");
    sb.append("    potentialdownloadbandwidthrevenue: ").append(toIndentedString(potentialdownloadbandwidthrevenue)).append("\n");
    sb.append("    potentialuploadbandwidthrevenue: ").append(toIndentedString(potentialuploadbandwidthrevenue)).append("\n");
    sb.append("    uploadbandwidthrevenue: ").append(toIndentedString(uploadbandwidthrevenue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

