/*
 * Sia
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.goobox.sync.sia.client.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse20013
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-01T00:02:50.340-05:00")
public class InlineResponse20013 {
  @SerializedName("downloadterabyte")
  private String downloadterabyte = null;

  @SerializedName("formcontracts")
  private String formcontracts = null;

  @SerializedName("storageterabytemonth")
  private String storageterabytemonth = null;

  @SerializedName("uploadterabyte")
  private String uploadterabyte = null;

  public InlineResponse20013 downloadterabyte(String downloadterabyte) {
    this.downloadterabyte = downloadterabyte;
    return this;
  }

   /**
   * The estimated cost of downloading one terabyte of data from the network.
   * @return downloadterabyte
  **/
  @ApiModelProperty(example = "1234", value = "The estimated cost of downloading one terabyte of data from the network.")
  public String getDownloadterabyte() {
    return downloadterabyte;
  }

  public void setDownloadterabyte(String downloadterabyte) {
    this.downloadterabyte = downloadterabyte;
  }

  public InlineResponse20013 formcontracts(String formcontracts) {
    this.formcontracts = formcontracts;
    return this;
  }

   /**
   * The estimated cost of forming a set of contracts on the network. This cost also applies to the estimated cost of renewing the renter&#39;s set of contracts.
   * @return formcontracts
  **/
  @ApiModelProperty(example = "1234", value = "The estimated cost of forming a set of contracts on the network. This cost also applies to the estimated cost of renewing the renter's set of contracts.")
  public String getFormcontracts() {
    return formcontracts;
  }

  public void setFormcontracts(String formcontracts) {
    this.formcontracts = formcontracts;
  }

  public InlineResponse20013 storageterabytemonth(String storageterabytemonth) {
    this.storageterabytemonth = storageterabytemonth;
    return this;
  }

   /**
   * The estimated cost of storing one terabyte of data on the network for a month, including accounting for redundancy.
   * @return storageterabytemonth
  **/
  @ApiModelProperty(example = "1234", value = "The estimated cost of storing one terabyte of data on the network for a month, including accounting for redundancy.")
  public String getStorageterabytemonth() {
    return storageterabytemonth;
  }

  public void setStorageterabytemonth(String storageterabytemonth) {
    this.storageterabytemonth = storageterabytemonth;
  }

  public InlineResponse20013 uploadterabyte(String uploadterabyte) {
    this.uploadterabyte = uploadterabyte;
    return this;
  }

   /**
   * The estimated cost of uploading one terabyte of data to the network, including accounting for redundancy.
   * @return uploadterabyte
  **/
  @ApiModelProperty(example = "1234", value = "The estimated cost of uploading one terabyte of data to the network, including accounting for redundancy.")
  public String getUploadterabyte() {
    return uploadterabyte;
  }

  public void setUploadterabyte(String uploadterabyte) {
    this.uploadterabyte = uploadterabyte;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20013 inlineResponse20013 = (InlineResponse20013) o;
    return Objects.equals(this.downloadterabyte, inlineResponse20013.downloadterabyte) &&
        Objects.equals(this.formcontracts, inlineResponse20013.formcontracts) &&
        Objects.equals(this.storageterabytemonth, inlineResponse20013.storageterabytemonth) &&
        Objects.equals(this.uploadterabyte, inlineResponse20013.uploadterabyte);
  }

  @Override
  public int hashCode() {
    return Objects.hash(downloadterabyte, formcontracts, storageterabytemonth, uploadterabyte);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20013 {\n");
    
    sb.append("    downloadterabyte: ").append(toIndentedString(downloadterabyte)).append("\n");
    sb.append("    formcontracts: ").append(toIndentedString(formcontracts)).append("\n");
    sb.append("    storageterabytemonth: ").append(toIndentedString(storageterabytemonth)).append("\n");
    sb.append("    uploadterabyte: ").append(toIndentedString(uploadterabyte)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

